markdown: redcarpet
highlighter: pygments
permalink: /:title

url: https://www.openkeychain.org
enforce_ssl: www.openkeychain.org   # without any protocol
baseurl: 

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed