markdown: redcarpet
highlighter: pygments
permalink: /:title

url: https://www.openkeychain.org
baseurl: 

redcarpet:
  extensions: [strikethrough, tables, with_toc_data]

sass:
  sass_dir: public/css
  style: :compressed